spring.application.name=shopping_cart
spring.datasource.url=jdbc:mysql://localhost:3306/ecomerce_db

spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dauphongdz@gmail.com
spring.mail.password=qvog hvyp klju cgrn

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

